FROM azul/zulu-openjdk-alpine:21-jdk

ARG DB_DRIVER_CLASS_NAME
ARG DB_PASSWORD
ARG DB_URL
ARG DB_USER
ARG LOG_HOME
ARG SERVER_PORT
ARG SPRING_PROFILES_ACTIVE
ARG APP_VERSION
ARG DOCKER_PORT

ENV DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV LOG_HOME=${LOG_HOME}
ENV SERVER_PORT=${SERVER_PORT}
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}

COPY build/libs/session-auth-server-0.0.1-SNAPSHOT.jar /app/session-auth-server.jar

EXPOSE ${DOCKER_PORT}

ENTRYPOINT ["java", "-jar", "/app/session-auth-server.jar"]