spring:
  profiles:
    active: local
  application:
    name: session-auth-server
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  session:
    store-type: redis

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/session
    encoding:
      charset: utf-8
      enabled: true
      force: true
    session:
      cookie:
        name: SESSIONID
        path: /
        http-only: true
        secure: false
      timeout: 30m
  forward-headers-strategy: framework

ats-session-auth:
  allow-swagger-without-login: false
  password-encoder-type: bcrypt
  cors-allowed-origins:
    - '*'

springdoc:
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    enabled: false
    csrf:
      enabled: true
  show-login-endpoint: true

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: embedded
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    enabled: true

ats-session-auth:
  allow-swagger-without-login: true


---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    enabled: true


---
spring:
  config:
    activate:
      on-profile: prod

server:
  servlet:
    session:
      cookie:
        domain: ats.aikusoni.com # example
        secure: true

springdoc:
  swagger-ui:
    enabled: false