spring:
  profiles:
    active: local
  application:
    name: session-auth-server
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/session
    encoding:
      charset: utf-8
      enabled: true
      force: true

ats-session-auth:
  allow-swagger-without-login: false
  password-encoder-type: bcrypt
  cors-allowed-origins:
    - '*'

springdoc:
  swagger-ui:
    display-request-duration: true
    disable-swagger-default-url: true
    enabled: false
    csrf:
      enabled: true
  show-login-endpoint: true

---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always


springdoc:
  swagger-ui:
    enabled: true

ats-session-auth:
  allow-swagger-without-login: true


---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    enabled: true


---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false