name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  bootjar-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          gradle-version: 8.5

      - name: Build Spring Boot application with Gradle
        run: ./gradlew clean bootJar --info --stacktrace
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: List build/libs contents
        run: ls -la build/libs/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/libs/*.jar

  docker-build-and-publish-to-docker-hub:
    name: Build and Publish Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: bootjar-build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git commit SHA for versioning
        id: vars
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t aikusoni/ats-session-auth-server:${{ env.COMMIT_SHA }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push aikusoni/ats-session-auth-server:${{ env.COMMIT_SHA }}

      - name: Tag the latest image
        run: |
          docker tag aikusoni/ats-session-auth-server:${{ env.COMMIT_SHA }} aikusoni/ats-session-auth-server:latest
          docker push aikusoni/ats-session-auth-server:latest