name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          gradle-version: 8.5

      - name: Build Spring Boot application with Gradle
        run: ./gradlew bootJar

      - name: Get Git commit SHA for versioning
        id: vars
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t aikusoni/ats-session-auth-server:${{ env.COMMIT_SHA }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push aikusoni/ats-session-auth-server:${{ env.COMMIT_SHA }}

      - name: Tag the latest image
        run: |
          docker tag aikusoni/ats-session-auth-server:${{ env.COMMIT_SHA }} aikusoni/ats-session-auth-server:latest
          docker push aikusoni/ats-session-auth-server:latest
